### ISSUE TITLE
variable length strings in metadata prevent opening loomR output in loompy

### ISSUE THREAD

**Issue by ekernf01** [mojaveazure/loomR#45]
The loompy specification says that strings must have fixed length. Using `loomR` version 0.2.0, I get hdf5 files that store strings as variable-length. Then, when I try to open them in Python, `ValueError: Column attribute 'whatever' dtype object is not allowed`.

```

$ python test_reader.py
Traceback (most recent call last):
  File "test_reader.py", line 8, in <module>
    loompy.connect("temp.loom")
  File "//anaconda/lib/python3.6/site-packages/loompy/loompy.py", line 1149, in connect
    return LoomConnection(filename, mode, validate=validate, spec_version=spec_version)
  File "//anaconda/lib/python3.6/site-packages/loompy/loompy.py", line 85, in __init__
    raise ValueError("\n".join(lv.errors) + f"\n{filename} does not appead to be a valid Loom file according to Loom spec version '{spec_version}'")
ValueError: Column attribute 'sample.LETTERS..size...100..replace...T.' dtype object is not allowed
For help, see http://linnarssonlab.org/loompy/format/
temp.loom does not appead to be a valid Loom file according to Loom spec version '2.0.1'

```

Here's the code I use to reproduce this bug. 

[loom_testing.zip](https://github.com/mojaveazure/loomR/files/3233073/loom_testing.zip)

Version info:

[r_session_info.txt](https://github.com/mojaveazure/loomR/files/3233085/r_session_info.txt)

```
python version: 3.6.8 |Anaconda custom (64-bit)| (default, Dec 29 2018, 19:04:46)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
numpy version: 1.13.3
loompy version: 2.0.17
```

**Comment by ekernf01** [comment]
Reading the loomR code, I don't see any place where the metadata type is explicitly set. Is it possible to specify the type of a field using hdf5r?
